### ISSUE TITLE
Suggestion to remove the word 'Extension' from statcard lines

### ISSUE THREAD

**Issue by Theren03** [Addysaurus/lang_modding#10]
Currently, these two lines on plane statcards are cut off and must scroll to display the full text, which is annoying. The word 'Extension' is superfluous and can be removed.
![image](https://github.com/Addysaurus/lang_modding/assets/15804650/7ced03a4-6ccc-43aa-93e4-1dbae75dfa53)

**Comment by Addysaurus** [comment]
Will be added in next update.

**Comment by Addysaurus** [comment]
Added in 1.08.56!
