### ISSUE TITLE
[1.08.58] USA Missing and Outdated Strings

### ISSUE THREAD

**Issue by Theren03** [Addysaurus/lang_modding#11]
Missing:
he_or_tank/name
he_or_tank/name/short
modification/MAW_system_heli_false_thermal_targets_large
sap_hei_t/name
sap_hei_t/name/short
weapons/12_7mm_M80_20_user_machinegun
weapons/105mm_t140e3_user_cannon

Outdated (missing yellow and orange text):
7.62 mm FN MAG 60-40 machine gun
7.62 mm M37 machine gun
7.62 mm M134 Minigun machine gun
7.7 mm Type 97 machine gun
7.92 mm MG 17 machine gun
12.7 mm GAU-19 machine gun
12.7 mm Ho-103 machine gun
12.7 mm M85 machine gun
13 mm MG 131 machine gun
20 mm AN/M2 cannon
20 mm Browning-Colt Mk12 Mod 0 cannon
20 mm Browning-Colt Mk12 Mod 3 cannon
20 mm GAU-4 cannon
20 mm Hispano 404 cannon
20 mm MG 151 cannon
20 mm Mk. 11 cannon
20 mm Mk. 11 mod 5 cannon
20 mm M139 cannon
20 mm M195 cannon
20 mm M197 cannon
20 mm Rh202 cannon
20 mm Type 99 Model 1 cannon
25 mm GAU-12U cannon
25 mm GAU-12/U cannon
25 mm LW25 cannon
25 mm M242 cannon
30 mm ADEN Mk. 4 cannon
30 mm GAU-8/A
30 mm GAU-13/A cannon
30 mm LR30 cannon
37 mm M4 cannon
37 mm M9 cannon
37 mm M10 cannon
40 mm Dual Automatic Gun M2
40 mm M266 automatic cannon
57 mm 6pdr OQF Mk.III cannon
57 mm M1 cannon
57 mm ZIS-2 cannon
66 mm smoke grenade launcher
70 mm Hydra-70 M247 rocket
75 mm M2 howitzer
75 mm M1897A4 cannon
75 mm M2 cannon
75 mm M3 cannon
75 mm M6 cannon
75 mm M10 cannon
75 mm T13E1 cannon
75 mm XM274 cannon
76 mm smoke grenade launcher
90 mm M3 cannon
90 mm M3A1 cannon
90 mm M36 cannon
90 mm M41 cannon
90 mm M54 cannon
90 mm T15E1 cannon
90 mm T15E2 cannon
90 mm T208E9
105 mm M4 howitzer
105 mm M68 cannon (M60A1 AOS uses a different M68 than the R/PE and TTS I guess)
105 mm T5E1 cannon
105 mm T5E2 cannon
105 mm T140E2 cannon
105 mm XM35 cannon
114 mm M8 rocket
120 mm IMI MG22251 cannon
120 mm M58 cannon
120 mm T53 cannon
152 mm gun/launcher M81
152 mm M162 gun/launcher
152 mm XM150E5 gun/launcher
155 mm T7 cannon

BGM-71 TOW ATGM
BGM-71C I-TOW ATGM
FFAR Mighty Mouse rocket
FIM-92 Stinger
Guided Missile System, Aerial Intercept, M54A2
HVAR rocket
Launcher, Tubular, Guided Missile, M220A1, Dual Launcher
M261
MGM-166A LOSAT Launch System
MIM-146A ADATS
Roland SAM
Smoke grenade launcher
turret (Secondary Weapon name for Huey door turrets)
Turret: 40 mm M75 grenade launcher
Turret: 40 mm M129 grenade launcher
Zuni Mk32 Mod 0 ATAP rocket

100 lb AN-M30A1 bomb
250 lb AN-M57 bomb
250 lb LDGP Mk. 81 bomb
250 lb Mk 81 Snakeye high-drag tail fin retarded bomb
300 lb H.E. M31 bomb
500 lb AN-M64A1 bomb
500 lb LDGP Mk. 82 bomb
500 lb Mk 82 AIR ballute-type retarded bomb
500 lb Mk 82 Snakeye high-drag tail fin retarded bomb
600 lb H.E. M32 bomb
750 M117 cone 45 bomb
1000 lb AN-M65A1 bomb
1000 lb AN-M65A1 Fin M129 bomb
1000 lb GP Mk9 bomb
1000 lb A.P. AN-MK 33 bomb
1000 lb LDGP Mk. 83 bomb
1000 lb Mk 83 AIR ballute-type retarded bomb
1000 lbs Type A Mark I aircraft laid magnetic mine
1600 lb AN-Mk. 1 armor-piercing bomb
2000 lb AN-M66A2 bomb
2000 lb LDGP Mk. 84 bomb
2000 lb LDGP Mk. 84 Air bomb
3000 lb M118 Demolition bomb
4000 lb AN-M56 bomb
FFAR Mighty Mouse rocket
FFAR Mighty Mouse rocket M439
HVAR rocket
M8 rocket
Mk. 13-6 torpedo (2216 lbs)
Mk. 13-6 Case Torpedo (2216 lbs)
1000 lb Mk. 79 Mod 1 incendiary bomb
BLU-1 incendiary bomb
BLU-27/B incendiary bomb
Mk. 77 mod 2 incendiary bomb
Mk. 77 mod 4 incendiary bomb
Mk. 78 incendiary bomb
Tiny Tim rocket
Zuni Mk32 Mod 0 ATAP rocket

Other:
AIM-9L Sidewinder AAM-IR - does not match other missiles (Guided Missile, Air to Air, AIM-9...)
    Only on some planes

**Comment by Addysaurus** [comment]
Jesus christ this is a big list. Not sure all of these can be fixed in the next update. I am slowly going through these bit by bit. Thank you so much for the giant list though. This will make my job much easier. The AIM-9L bug and the missing strings will definitely be fixed next patch.

**Comment by Theren03** [comment]
no worries, split it up however you want :3

**Comment by Addysaurus** [comment]
I'm going to do all of the American stuff this update, but the foreign stuff is saved for later. The MG 17, MG 151, Rh202, and all those other German ones will happen eventually. The Hispano 404 is on hold because I've been searching for sources on that one for quite a while. The Type 97, Type 99 Model 1, and Ho-103 will happen whenever I hate myself enough to even think of touching Japanese weapon designations.

**Comment by Addysaurus** [comment]
Didn't mean to close. Oops.

**Comment by Theren03** [comment]
Sources for GAU cannons:
- 12.7 mm GAU-19/A
  - Page 101 on Source 1
  - Page 119 on Source 2
- 20 mm GAU-4
  - Page 188 on Source 1
  - Page 159 on Source 3
  - Page 116 on Source 4
- 25 mm GAU-12/U (on AV-8B)
  - Page 80 on Source 1
  - Page 6 and 161 on Source 3
  - Page 116 on Source 4
- 25 mm GAU-12/U (on LAV-AD)
  - Page 103 on Source 1
  - Page 162 on Source 3
  - Page 106 on Source 4
- 30 mm GAU-8/A
  - Page 80 on Source 1
  - Page 15 and 162/163 on Source 3
  - Page 70 and 88 on Source 4
- 30 mm GAU-13/A
  - Page 80 on Source 1
  - Page 163 on Source 3
  - Page 119 on Source 4


Sources:
- Source 1: _Rapid Fire: The Development of Automatic Cannon, Heavy Machine-Guns and Their Ammunition for Armies, Navies and Air Forces_ by  Anthony G. Williams (https://archive.org/details/FirearmsTheDevelopmentOfAutomaticCannonHeavyMachineGunsAndTheirAmmunitionForArmiesNaviesAndAirForces)

- Source 2: _April 2018 - The Concise Global Industry Guide: Military Helicopter Handbook Issue 31_ by Shepard (https://archive.org/details/military-helicopter-handbook-april-2018)

- Source 3: _Encyclopedia of Modern U.S. Military Weapons_ by  Timothy M. Laur and Steven L. Llanso (https://archive.org/details/Encyclopedia_of_Modern_US_Military_Weapons)

- Source 4: _The Gatling Gun: 19th Century Machine Gun to 21st Century Vulcan_ by Joseph Berk (https://archive.org/details/the-gatling-gun-19th-century-machine-gun-to-21st-century-vulcan-paladin-press)

**Comment by Theren03** [comment]
Colt Mk 11 and Mk 12 20 mm cannons:

20 mm Mk 12:
- Source 1: _NAVWEPS OP 1886 20-MM Aircraft Guns Mark 12 Mods 0, 2, and 3 - Description, Operation, and Maintenance Revision 1, N.D._ - [PDF Download](https://drive.google.com/file/d/1Qadku999lrNkKvifuJ4MzeMlKQ8EBf4G/view?usp=sharing)
- Source 2: _MIL-STD-637A - Machine and Automatic Guns and Machinegun Trainers Through 30-mm_ - [PDF View](https://drive.google.com/file/d/1Sc_aDGyOn3RnR8EsqQkzg6AGAQZAW0Xp/view)


20 mm Mk 11:
The A-4, A-6, F-4J, etc. all use the Navy's 20 mm Mk 4 Gun Pod, which contains the 20 mm Mk 11 Mod 4 cannon. At first glance, the CH-34A also uses the same Mk 4 Gun Pod, but as it turns out it uses the Hughes EX-1 Gun Pod, which was a modification of the Mk 4 Gun Pod. Thus, it appears all US aircraft with the Mk 11 cannon use the Mod 4 variant.

- Source 1: _AD 427049 - Defense Documentation Center for Scientific and Technical Information_ - (http://www.chinalakealumni.org/Downloads/1963%20HTC-63-56.pdf)
- Source 2: _MN 10121a - United States Navy Training Film_ - [YouTube Video](https://www.youtube.com/watch?v=_6c4k2RsVpc)

**Comment by Addysaurus** [comment]
Fixed in 1.08.59!
