### ISSUE TITLE
[1.08.60] Minor Errors and Goofs

### ISSUE THREAD

**Issue by Theren03** [Addysaurus/lang_modding#15]
![image](https://github.com/Addysaurus/lang_modding/assets/15804650/664a6504-4b71-4d20-95ba-09a3a3ee688b)
MiG-23ML was stated to be changed to "23-12A" in changelog, but is "23-12" in game.

![image](https://github.com/Addysaurus/lang_modding/assets/15804650/4fe886be-76af-4af2-bf00-8f977d63921f)
Version number is still 1.08.59

**Comment by Addysaurus** [comment]
Fixed in 1.08.61!
