### ISSUE TITLE
[1.08.61] Missing Strings on Ground Vehicles and Helicopters

### ISSUE THREAD

**Issue by Theren03** [Addysaurus/lang_modding#16]
Germany:

- RakJPz 2 (HOT) - weapons/136mm_k3s_hot_launcher_user_cannon
- UH Tiger - weapons/us_aim92_stinger_atas_tiger (+/short)

Britain:
- Swingfire - weapons/170mm_bae_swingfire_fv438_launcher_user_cannon
- Challenger 2 TES (2H) - weapons/7_62mm_l37a2_enforcer_user_machinegun
- Aoacge A.H. Mk.1 - weapons/countermeasure_split_launcher_jet_only_flare_large (+/short)

Japan:
- 60 APC (ATM-1) - weapons/120mm_type_64_mat_launcher_user_cannon
- 99 HSP - weapons/155mm_type_99_l52_user_cannon

China:
- T-34-85 (1960s) - weapons/85mm_Type_56_user_cannon

France:
- AMX 10P - weapons/20mm_m693_amx_10_user_cannon
- Leclerc (all) - weapons/12_7mm_M2_HB_user_machinegun_for_leclerc
- Tigre (all) - weapons/us_aim92_stinger_atas_tiger (+/short)

Sweden:
- ikv 72 - weapons/75mm_kan_m41_open_turret_user_cannon

**Comment by Addysaurus** [comment]
Will be fixed in 1.08.62!

**Comment by Theren03** [comment]
Found one more:
- M113A1 (TOW) (all) - 127_bgm_71_tow

**Comment by Addysaurus** [comment]
This will also be fixed in 1.08.62!

**Comment by Addysaurus** [comment]
Fixed in 1.08.62!
