### ISSUE TITLE
[1.08.61] Missing Strings for New Default Air Ordinance

### ISSUE THREAD

**Issue by Theren03** [Addysaurus/lang_modding#17]
All strings also have a /short variant

- F-14A-65-GR - weapons/us_aim54a_default
- F-14B-150-GR - weapons/us_aim54c_default
- F-15A-18-MC (MSIP), F-15J (1983), F-15A-18-MC (MSIP) (Israel) - weapons/us_aim7m_sparrow_f_15_default
- AV-8B Radar, F-15C-39-MC (MSIP II), F-16C-50-CF (2007), F-4F KWS-LV, F-15J (2003), AV-8B Plus (Italy), JAS 39 C EBS HU, F-16AM-15-CF, F-15C-39-MC (MSIP II) (Israel) - weapons/us_aim_120a_default
- Yak-141, Su-27S - weapons/su_r_27r_default
- MiG-29SMT, Su-27SM - weapons/su_r_77_default
- Tornado F. Mk. 3 (UK and Italy) - weapons/uk_skyflash_aim_7_dogfight_tornado_default
- Harrier G.R. Mk. 7 - weapons/us_aim9l_sidewinder_default_bol_pod
- Sea Harrier F.A. Mk. 2, Tornado F. Mk. 3 (AOP) - weapons/us_aim_120b_default
- Gripen C (UK) - weapons/r_darter_default
- F-4EJ Kai - weapons/us_aim7f_sparrow_default
- J8F - weapons/su_pl8_default
- Su-27SK (China) - weapons/su_r_27r1_default
- J11A (MLU) - weapons/su_rvv_ae, weapons/su_rvv_ae_default
- Mirage 4000 (1986) - weapons/fr_matra_super_530d_default
- Mirage 2000 5F - weapons/fr_mica_em_default
- JAS 39 A - weapons/swd_rb71_default
- JAS 39 C - weapons/swd_rb74m_default, weapons_rb99_default
- Kurnass 2000, F-16A-15OCU-CF - weapons/il_pyton_3_default 
- F-16D-40-CF - weapons/il_derby_default

(lmao pyton)

**Comment by Addysaurus** [comment]
These will all be fixed in 1.08.62! The RVV-AE one was already on my radar (pun intended).

**Comment by Addysaurus** [comment]
Fixed in 1.08.62!
