### ISSUE TITLE
[1.08.67] Missing Strings on the IRIAF F-14A

### ISSUE THREAD

**Issue by Theren03** [Addysaurus/lang_modding#18]
- country_iran
- modification/ir_sedjil
- modification/ir_fakour_90
- modification/ir_yasser
- f_14a_iriaf/desert
- f_14a_iriaf/desert2

**Comment by Addysaurus** [comment]
You need to delete the lang folder and restart your game to have the new lang files added to the base files. Then reinstall the mod by dropping the files into the new lang folder.

**Comment by Theren03** [comment]
whoops my B, always forget about doing that

**Comment by Addysaurus** [comment]
Is okii.
