### ISSUE TITLE
[1.09.00] Errors in Ordinance Strings

### ISSUE THREAD

**Issue by Theren03** [Addysaurus/lang_modding#21]
It appears some ordinance strings have extra text. Some examples:

![image](https://github.com/user-attachments/assets/20c091c5-97f6-48f3-b876-5badf84ff356)
![image](https://github.com/user-attachments/assets/587df854-44c7-4538-8940-59ffa4c5628b)

Other vehicles just have their default game strings for ordinance names (no color tags and such):
![image](https://github.com/user-attachments/assets/62b59182-8b18-497f-94d7-d617d9956e87)
![image](https://github.com/user-attachments/assets/e1699340-a6f8-43b0-8b8a-d5ff0856b83c)

This appears to be a far reaching bug, as nearly every vehicle is affected in one way or another as far as I can tell.

**Comment by Addysaurus** [comment]
Will be fixed in hotfix 1.09.01. Sorry, changed the mod's format and my CSV editor didn't remove quotes properly.
