### ISSUE TITLE
KAB-500S and Su-24's modifications' tree

### ISSUE THREAD

**Issue by PheakTraER** [Addysaurus/lang_modding#23]
![image](https://github.com/user-attachments/assets/cc234d69-9d92-453c-8a3f-0f93a8fde29c)
Name of modification for KAB-500S labeled as Su-24M2 in Mig-29SMT's Modifications' tree
![image](https://github.com/user-attachments/assets/46042b19-9a09-4a3b-9186-680e9c756b57)
But in Su-24's modifications' tree it's missing its line for KAB-500S and "su_fab_250_500"

**Comment by Addysaurus** [comment]
Hi. So sorry that it took me forever to see this. The modification has been renamed to FAB-500 / KAB-500S-E and this will be fixed in 1.09.04.

**Comment by BergenCountyGSA** [comment]
Fixed in 1.09.04!

**Comment by Addysaurus** [comment]
Fixed in 1.09.04!
