### ISSUE TITLE
spawning a helicopter test drive stretches the country hud when you exit the test drive

### ISSUE THREAD

**Issue by bingobangobongo212** [Addysaurus/lang_modding#24]
![image](https://github.com/user-attachments/assets/b4460a3e-2776-436c-9677-b22b0b02d752)

resets upon test driving a tank

**Comment by Theren03** [comment]
This is a bug with war thunder. It has to be fixed by gaijin. I have a report on the bug tracker already.

 https://community.gaijin.net/issues/p/warthunder/i/NI0pG6PeiDPD

**Comment by Addysaurus** [comment]
Yeah it is a big issue. I hope Gaijin fixes it.

**Comment by Addysaurus** [comment]
For the major 10 nations, the long country names have been removed until Gaijin fixes this.
