### ISSUE TITLE
Missing localization's weapon name

### ISSUE THREAD

**Issue by PheakTraER** [Addysaurus/lang_modding#26]
![image](https://github.com/user-attachments/assets/0f886301-ad19-4c8b-a747-bcd1a1f6001c)
Yellow Line: No Name
Green Line: Missing langmod custom name
![image](https://github.com/user-attachments/assets/3df64519-c8d4-453b-8f55-ecb00874cea9)
Missing missile Guidance type name for "Laser + In Ordinance Guidance + Global Navigation Satellite System"
I wont be posting more images but here are things ive found are:
PGM 2000 guided bomb, PGM 500 guided bomb (also its guidance type name (missile/guidance/tv+IOG) (completely separate from IIR ones)
1000 lb H.E. M.C. Mk.13 Bomb (also the High Drag variant)
4000 lb H.C. Mk. IV bomb
H.C. 4000 lb Mk. II bomb
1000 lb G.P. Mk. I bomb
1000 lb M.C. Mk. I bomb
500 lb H.E. M.C. Mk. II Bomb
500 LB S.A.P Mk.II bomb (AP bomb)
2000 LB A.P Mk.I bomb
Mk. M2 540 lb bomb
M.C. 500 lb Mk. I
G.P. 250 lb Mk. I
G.P. 250 lb Mk. IV bomb
G.P. 500 lb Mk. IV bomb
1000 lb L.D H.E. M.C. Mk. 1
H.E. M.C. Mk.1 No.118 540 lb bomb (its a high drag bomb by the way)
RP rocket
RP-3 rocket
70 mm CRV7 M247 rocket
70 mm Hydra-70 M247 rocket
SNEB type 23 rocket
AP Mk. II rocket
AP Mk. I rocket
Triplex R.P. rocket
Uncle Tom rocket
18 inch Mark XV torpedo (1801 lbs)
18 inch mark XII torpedo (1548 lbs)
ZT3A2 Ingwe air-to-ground missiles
AS.12 air-to-ground missile
AS.11 air-togroun
20 mm Oerlikon KAD-8 cannon (Ammo: 570)

**Comment by Addysaurus** [comment]
The missing weapons and guidance lines will be added in 1.10.01. As for all these other names listed, are they also missing? Or do you mean they just don't have proper names yet? If it's the latter, I know. There is only so much time to do reworks and 60,000 naval reworks are eating up our time right now.

**Comment by PheakTraER** [comment]
they're missing their proper name yes. either way good luck with naval rework :ohgod:

**Comment by Addysaurus** [comment]
Forgot to say but this was fixed in 1.10.01.
