### ISSUE TITLE
Su-27 is wrong model

### ISSUE THREAD

**Issue by Zachattack525** [Addysaurus/lang_modding#27]
Due to having the AL-31F engine, the Su-27 is actually specifically an Su-27S

**Comment by Addysaurus** [comment]
Su-27S is not a real designation. The "S" likely comes from the Izdeliye T-10S. The Izdeliye T-10 and the Izdeliye T-10S were both the Su-27, and it is likely that the "S" was simply tacked onto the Su-27 coloquially for the purposes of distingushing between the Izdeliey T-10 and T-10S. Su-27S is not a real designation.

This mod used to have it as the Su-27S, but it was changed back to the Su-27 for this reason.

**Comment by Addysaurus** [comment]
If you have a historical, primary source for the name Su-27S being real, please present it here and the name will likely be changed.
