### ISSUE TITLE
Some ordinance missing strings

### ISSUE THREAD

**Issue by Theren03** [Addysaurus/lang_modding#3]
As title says.

AIM-7 (All), AIM-54 (All), R-23R, R-24R, R-27R (All), R-27ER (ALL), AS.34, Skyflash (All), Aspide-1A, Matra Super 530D, Rb 71,
- missile/shootDown
- missile/shootDown/headOnAspect

AS.34
- missile/shootDown/allAspects

R-24R
- missile/guidance/SARH+IOG

R-27R (All), R-27ER (All)
- missile/guidance/SARH+IOG+DL

Kh-38MT
- missile/guidance/ir+IOG

Skyflash Dogfight
- weapons/uk_skyflash_aim_7_dogfight_tornado

Matra Super 530F (but only on the Mirage 2000's, it's fine on the 4000)
- weapons/fr_matra_super_530f_mirage_2000

**Comment by Addysaurus** [comment]
Thanks for the report! Fixed in 1.08.35.
