### ISSUE TITLE
List of plane engines with missing/incorrect strings

### ISSUE THREAD

**Issue by Theren03** [Addysaurus/lang_modding#4]
USA
- J79-GE-7a: 'A' should be capitalized
- Pratt & Whitney R-2800-18w, -42w, -10w: 'W' should be capitalized
- Allison TF-41-A-1, -2: Remove first hyphen to match other TF engines
- Pratt & Whitney R1830-64, R1830-92, R1830-65: Add hyphen after 'R' to match other P&W engines
- Pratt & Whitney J57P8, J57P21: Add hyphen before and after 'P' to match other P&W engines
- Pratt & Whitney J52-P-8As: remove 's'
- F-4S missing string: engine_model/j79_ge_10b

Germany
- Alpha Jet A missing strings: engine_manufacturer/snecma_turbomeca_larzac, engine_model/04_c6

Britain
- Sea Harrier F.R.S. Mk. 1 and Mk. 1 (Phase 1) missing string: engine_model/pegasus_104
- Strikemaster Mk. 88 missing string: engine_model/viper-535

Japan
- B7A2 (Homare 23) missing string: engine_model/homare_23

China
- Shenyang Liming WP-6a, WP-7a: 'A' should be capitalized
- **EDIT: Meant WP-7b should have a capital 'B'**
- Wright Cyclone R-1820G2: Add hyphen before 'G2'

Italy
- A-11B missing string: engine_model/spey_807
- AV-8B Plus missing string: engine_model/f402-rr-408

France
- Alpha Jet E missing strings: engine_manufacturer/snecma_turbomeca_larzac, engine_model/04_c5

Sweden
- S 9 C missing string: engine_model/r1830-45

**Comment by Addysaurus** [comment]
Thank you so much for all the reports. I'll add the missing engine names. Do you have actual sources for the J79-GE-7a, R-2800s, TF-41-A-1 amd A-2, R1830s, J57s, J52, WP-6a, WP-7a, and R-1820 changes?

**Comment by Addysaurus** [comment]
Some of the changes I will make for consistency, but do you have documentation or sources?

**Comment by Theren03** [comment]
R-1820-G2: Page 109 on _Milestones of Aviation: Smithstonian Institution National Air and Space Museum_ edited by John T. Greenwood (https://archive.org/details/milestonesofavia0000unse/page/108)

R-1830's: 
- 64: Page 34 on _PBY: The Catalina Flying Boat_ by Roscoe Creed (https://archive.org/details/pbycatalinaflyin00cree/page/34)
- 65: Page 14 on _B-24 Liberator in detail_ by Bert Kinzey (https://archive.org/details/b24liberatorinde0000kinz/page/14)
- 92: Page 38 on _Erection & Maintenance Instructions for Model PBY-5A Airplane_ (https://archive.org/details/erection-maintenance-pby-1942/page/38)

R-2800's: _R-2800: Pratt & Whitney's Dependable Masterpiece_ by Graham White (https://archive.org/details/r2800prattwhitne0000whit)
- 10W: page 5
- 18W: page 185
- 42W: page 272

J52-P-8A: Page 12 of _Aeroguide 15: Grumman A-6E Intruder_ by Roger Chesneau (https://archive.org/details/aeroguide-15-grumman-a-6e-intruder./page/12)
- I know it technically says J52-P-8As and not just 8A, but its pluralizing the name in the context of the sentence.

J57's:
- P-8: Page 196 of _Ed Heinemann Combat Aircraft Designer_ by Edward H. Heinemann (https://archive.org/details/edheinemanncomba0000hein/page/196)
- P-21: Page 21 of _Osprey Air Combat: Republic F-105 Thunderchief_ by David Anderton (https://archive.org/details/osprey-air-combat-republic-f-105-thunderchief./page/21)

J79-GE-7A: 
- Page 85 of _Lockheed F-104 Starfighter Vol. I F-104A/F-104F_ by Rafael de Madariaga Fernández (https://archive.org/details/f-104/F-104/page/84/)
- Page 45 of _Lockheed F-104 Starfighter (Crowood Aviation Series)_ by Martin Bowman (https://archive.org/details/f-104-starfighter/F-104%20Starfighter/page/n25)

TF41-A's:
- A-1: Page 1-3 of _T.O. 1A-7D-1 Flight Manual A-7D_ (https://archive.org/details/T.O.1A7D1FlightManualA7D20091972/page/n19)
- A-2: Page 2 of _A Revised Design Concept for the A-7E Approach Power Compensator System_ by David Haley Finney (https://archive.org/details/areviseddesignco1094516784/page/n7)


WP-6A: Page 68 on _Mikoyan-Gurevich MiG-19: The Soviet Union's First Production Supersonic Fighter_ by Yefim Gordon (https://archive.org/details/mikoyan-gurevich-mi-g-19-the-soviet-unions-first-production-supersonic-fighter/page/67)

WP-7B: Page 53 on _Dragon's Wings: Chinese Fighter and Bomber Aircraft Development_ by Andreas Rupprecht (https://archive.org/details/dragonswingschin0000rupp/page/52)

**Comment by Addysaurus** [comment]
Engine names added in 1.08.36.

**Comment by Addysaurus** [comment]
Engine names fixed in 1.08.37.
